services:
# name of image
  my-node-image:
# name of container
    container_name: express-container
    # will map with Dockerfile 
    ports:
      - "4000:4000"
  # For many variables, use .env file instead 
    env_file:
    - ./.env                    # Load all variables from .env file